import Head from 'next/head';
import { I18nextProvider } from 'react-i18next';
import i18n from '../utils/i18';
import MainLayout from '@/layouts/MainLayout';
import { Suspense } from 'react';
import Fallback from '@/shared/Fallback';

export default function Home() {
  return (
    <>
      <Head>
        <title>todo list</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='todo-icon' href='/todo.png' />
      </Head>
      <I18nextProvider i18n={i18n}>
        <MainLayout>
          <Suspense fallback={<Fallback />}></Suspense>
        </MainLayout>
      </I18nextProvider>
    </>
  );
}
